#---------------------------------#
#       build configuration       #
#---------------------------------#

version: '1.0.{build}'

image: Visual Studio 2017

init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

before_build:
  # Display .NET Core version
  - cmd: dotnet --version

build_script:
  - cmd: dotnet build CloneRegistry.sln

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - cmd: dotnet test .\TestCloneRegistry\TestCloneRegistry.csproj

deploy: off