#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: CloneRegistry.sln      # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: normal

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - TestCloneRegistry.dll

# scripts to run before tests
before_test:
    - setenv.bat